# Generated by Django 4.2.16 on 2024-11-13 23:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message="Billing ID must be in the format 'XXX-XX-XXXX'.", regex='^\\d{3}-\\d{2}-\\d{4}$')])),
                ('date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('dropoff_time', models.TimeField()),
                ('distance_covered', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('total_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('source_location', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
        ),
    ]
