# Generated by Django 4.2.16 on 2024-11-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='passenger_count',
            field=models.IntegerField(default=1),
        ),
    ]
