[supervisord]
nodaemon=true

[program:django]
command=sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn uber_backend.wsgi:application --bind 0.0.0.0:8002"
autostart=true
autorestart=true

[program:kafka_consumer]
command=sh -c "sleep 10 && python manage.py driver_consumer"
autostart=true
autorestart=true
stdout_logfile=/var/log/kafka_consumer.log
stderr_logfile=/var/log/kafka_consumer.err
